#!/usr/bin/env bash

set -euo pipefail

source "$DOFILES_PATH/scripts_helper.sh"

##? Delete all docker volumes in your system
#?? 1.0.0
##?
##? Usage:
##?   delete-volumes
docs_parse "$@"

if docker ps >/dev/null 2>&1; then
  docker volumes rm $(docker volumes ls -q)
else
  echo "Docker daemon is not running! (ಠ_ಠ)"
fi
