#!/usr/bin/env bash

set -euo pipefail

source "$DOFILES_PATH/scripts_helper.sh"

##? Prune all docker stuff
#?? 1.0.0
##?
##? Usage:
##?   prune
docs_parse "$@"

docker stop $(docker ps -a -q)
yes | docker system prune -a
