#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Generates and copy to the clipboard a UUID
#?? 1.0.0
##?
##? Usage:
##?   uuid_code
docs::parse "$@"

uuid=$(uuidgen | tr '[:upper:]' '[:lower:]')
if platform::is_macos; then
	echo -n $uuid | pbcopy
	osascript -e 'display notification "'"$uuid"'" with title "UUID copied to the clipboard"'
elif platform::is_wsl; then
	echo -n $uuid | clip.exe
else
	echo -n $uuid | xclip -sel clipboard
	notify-send "UUID copied to the clipboard"
fi
