#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Add all files, commit with message and push to the current branch
#?? 1.0.0
##?
##? Usage:
##?   commit
##?   commit <message>
docs::eval "$@"

git add -A

if [ -z "$message" ]; then
  git commit 
else
  git commit -m"$1"
fi

git push
