#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Add all files and then a commit-no-sign
#?? 1.0.0
##?
##? Usage:
##?   commit-no-sign
##?   commit-no-sign <message>
docs::parse "$@"

git add -A

if [ -z "$message" ]; then
  git commit
else
  git commit -m"$1"
fi
