#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Show all ignored files
#?? 1.0.0
##?
##? Usage:
##?   show-ignored
docs::eval "$@"

git status --ignored -s | grep "\!\!"
