#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Post install dotfiles  
#?? 1.0.0
##?
##? Usage:
##?   post_install_dotfiles
docs::parse "$@"

echo "Installing gcloud..."
tar -xf $DOTFILES_PATH/support/google-cloud-sdk-349.0.0-darwin-x86_64.tar.gz -C $HOME
echo "Extracted into $HOME/google-cloud-sdk"
$HOME/google-cloud-sdk/install.sh --usage-reporting false --path-update false --install-python --command-completion false
echo "Installed"

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash

if platform::is_linux; then
    sudo apt-get update
    sudo apt update
    sudo apt install build-essential
    curl https://sh.rustup.rs -sSf | sh
    sudo apt-get install vim
    sudo apt-get install ripgrep
    cargo install git-delta
    sudo apt upgrade
    sudo apt-get upgrade
fi

