#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Post install dotfiles  
#?? 1.0.0
##?
##? Usage:
##?   post_install_dotfiles
docs::parse "$@"

echo "Installing gcloud..."
tar -xf $DOTFILES_PATH/support/google-cloud-sdk-349.0.0-darwin-x86_64.tar.gz -C $HOME
echo "Extracted into $HOME/google-cloud-sdk"
$HOME/google-cloud-sdk/install.sh --usage-reporting false --path-update false --install-python --command-completion false
echo "Installed"

