#!/usr/bin/env bash

set -euo pipefail

source "$DOFILES_PATH/scripts_helper.sh"

##? Prints the mysql general log
#?? 1.0.0
##?
##? Usage:
##?   general_log
docs_parse "$@"

MYSQL_LOG_PATH="/var/log/mysql_general.log"

sudo rm $MYSQL_LOG_PATH
sudo touch $MYSQL_LOG_PATH
sudo chmod 777 $MYSQL_LOG_PATH

mkdir -p /usr/local/etc/my.cnf.d
mysql -uroot -e "SET GLOBAL general_log = 'ON';"
mysql -uroot -e "SET GLOBAL general_log_file = '$MYSQL_LOG_PATH';"

tail -f $MYSQL_LOG_PATH
