#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Show databases
#?? 1.0.0
##?
##? Usage:
##?   show_dbs
##?   show_dbs <hostname> <user>
docs::parse "$@"

if [ -z "$hostname" ]; then
    URL='localhost'
else
    URL=$hostname
fi


if [ -z "$user" ]; then
  USER='root'
else
  USER=$user
fi


mysql -h "$URL" -u "$USER" -p <<MYSQL_SCRIPT
SHOW DATABASES;
MYSQL_SCRIPT

