#!/usr/bin/env bash

set -euo pipefail

source "$DOFILES_PATH/scripts_helper.sh"

##? Truncate all tables for a given database
#?? 1.0.0
##?
##? Usage:
##?   truncate_database <database_name>
docs_parse "$@"

mysql -uroot -N -B -e "SELECT CONCAT('SET FOREIGN_KEY_CHECKS=0; TRUNCATE TABLE $database_name.', TABLE_NAME, '; SET FOREIGN_KEY_CHECKS=1;') AS QUERY FROM information_schema.tables WHERE TABLE_SCHEMA = '$database_name';" | while read line; do
  echo "🔥 Executing: $line"
  mysql -uroot -e "$line"
done
