#!/usr/bin/env bash

set -euo pipefail

# shellcheck source=./../../modules/dotly/scripts/core/_main.sh
source "$DOTLY_PATH/scripts/core/_main.sh"


##? Changes db in config file
#?? 1.0.0
##?
##? Usage:
##?   change-db <dbName>
docs::parse "$@"

FILE=$PWD/application/config/database.php

if [ -f "$FILE" ]; then
    # shellcheck disable=SC2154
    sed -i "57s/.*/\$db['default']['database'] = '$dbName';/" $FILE
    echo "Regenerating db.."
    regendb
    echo "Compiling styles..."
    styles
    
    echo "DB Name changed correctly to $dbName"
else
    echo "Database config file not found. Make sure you are inside the platform folder."
fi

