#!/usr/bin/env bash

set -euo pipefail

# shellcheck source=./../../modules/dotly/scripts/core/_main.sh
source "$DOTLY_PATH/scripts/core/_main.sh"


##? Changes db in config file
#?? 1.0.0
##?
##? Usage:
##?   change-db <dbName>
docs::parse "$@"

FILE=$PWD/application/config/database.php

if [ -f "$FILE" ]; then
    numFileDatabase="$(grep -n '"database"' $FILE | head -n 1 | cut -d: -f1)"
    # shellcheck disable=SC2154
    sed -i "${numFileDatabase}s/.*/\$db[\"default\"][\"database\"] = '$dbName';/" $FILE
    echo "Regenerating db.."
    echo "Ejecutando regenerate_db" && curl -s "http://eventscase.loc/tools/regenerate_db"
    echo "Compiling styles..."
    echo "Ejecutando less_compile" && curl -s "http://eventscase.loc/tools/less_compile"
    echo ""
    echo "DB Name changed correctly to $dbName"
else
    echo "Database config file not found. Make sure you are inside the platform folder."
fi

