#!/usr/bin/env bash

set -euo pipefail

# shellcheck source=./../../modules/dotly/scripts/core/_main.sh
source "$DOTLY_PATH/scripts/core/_main.sh"


##? check merged branches to specific branch by author
#?? 1.0.0
##?
##? Usage:
##?   check-merged-branches <branchName> <authorName>
docs::parse "$@"

git branch -r --merged $1 --format='%(committerdate) %09 %(authorname) %09 %(refname)' | sort \
-k5n -k2M -k3n -k4n | grep "$2"

