#!/usr/bin/env bash

set -euo pipefail

# shellcheck source=./../../modules/dotly/scripts/core/_main.sh
source "$DOTLY_PATH/scripts/core/_main.sh"

##? Changes db in config file
#?? 1.0.0
##?
##? Usage:
##?   get-dbs <setting_path>
docs::parse "$@"


if [ -z "$setting_path" ] 
then
    CONFIGFILE=/etc/mydumpadmin/settings.conf
else
    CONFIGFILE=$setting_path
fi

if [[ ! -e $CONFIGFILE ]]; then
    echo "File doesn't exist"
    exit 0
fi

source $CONFIGFILE
CREDENTIALS="--defaults-file=$CREDENTIAL_FILE"

### Start database backups
if [ "$DB_NAMES" == "ALL" ]; then
    DATABASES=`$MYSQL $CREDENTIALS -h $MYSQL_HOST -P $MYSQL_PORT -Bse 'show databases' | grep -Ev "^(Database|mysql|performance_schema|information_schema)"$`
else
    DATABASES=$DB_NAMES
fi

if [ -n "$DB_NAMES_REGEX_DISCARDED" ]; then
    declare -a DBNAMES_TEMP
    for i in ${DATABASES[@]}; do # access each element of array
        [[ ! "$i" =~ $DB_NAMES_REGEX_DISCARDED ]] && DBNAMES_TEMP+=($i)
    done
    unset $DATABASES
    DATABASES=${DBNAMES_TEMP[@]}
fi

for database in ${DATABASES[@]}; do
  echo $database
done