[merge]
    command = "nvim"
   args = ["-d", "{{ .Destination }}", "{{ .Source }}", "{{ .Target }}"]

[diff]
    exclude = ["externals"]
    pager = "delta"

[git]
    autoCommit = true
    autoPush = true