#!/usr/bin/env bash

set -euo pipefail

source "$DOFILES_PATH/scripts_helper.sh"

##? Count files recursives in the current direcory
#?? 1.0.0
##?
##? Usage:
##?   count_files_recursive
docs_parse "$@"

find . -type f -print | wc -l
