#!/usr/bin/env bash

set -euo pipefail

source "$DOFILES_PATH/scripts_helper.sh"

##? Count files recursives in the current direcory disgregated per subdirectory
#?? 1.0.0
##?
##? Usage:
##?   count_files_recursive_per_directory
docs_parse "$@"

ls -d ./*/ | xargs -I _ sh -c "find \"_\" -type f | wc -l | xargs echo \"_\""
