#!/usr/bin/env bash

set -euo pipefail

source "$DOFILES_PATH/scripts_helper.sh"

##? Create a file with all the involved folders
#?? 1.0.0
##?
##? Usage:
##?   create <filename>
docs_parse "$@"

mkdir -p "$(dirname "$1")" && touch "$1"
