#!/usr/bin/env bash

set -euo pipefail

source "$DOFILES_PATH/scripts_helper.sh"

##? Show all broken symlinks in the current directory
#?? 1.0.0
##?
##? Usage:
##?   find_broken_symlinks
docs_parse "$@"

find -L . -type l
