#!/usr/bin/env bash

set -euo pipefail

source "$DOFILES_PATH/scripts_helper.sh"

##? Flat the current directory
#?? 1.0.0
##?
##? Usage:
##?   flat_this_dir
docs_parse "$@"

sudo find . -mindepth 2 -type f -exec mv -i '{}' . ';'
