#!/usr/bin/env bash

set -euo pipefail

source "$DOFILES_PATH/scripts_helper.sh"

##? Preview all files (in all folders) for the current directory
#?? 1.0.0
##?
##? Usage:
##?   navigate_and_preview_flatten_files
docs_parse "$@"

fzf --preview 'bat --color \"always\" {}'
