#!/usr/bin/env bash

set -euo pipefail

source "$DOFILES_PATH/scripts_helper.sh"

##? Replace newlines in a file with \n
#?? 1.0.0
##?
##? Usage:
##?   newline-for-line-ending <filePath>
docs_parse "$@"

sed -E ':a;N;$!ba;s/\r{0,1}\n/\\n/g' $filePath