#!/usr/bin/env bash

set -euo pipefail

source "$DOFILES_PATH/scripts_helper.sh"

##? Fuzzy find a file with an active preview
#?? 1.0.0
##?
##? Usage:
##?  search_file_with_preview
docs_parse "$@"

fzf --preview 'bat --style=numbers --color=always --line-range :500 {}'

