#!/usr/bin/env bash

set -euo pipefail

source "$DOFILES_PATH/scripts_helper.sh"

##? Shows the size of the current directory
#?? 1.0.0
##?
##? Usage:
##?   size_of_directory
docs_parse "$@"

ncdu --color dark -rr -x
