# This is a basic workflow to help you get started with Actions

name: Test CI

on:
  push:
    branches:
      - master
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: addnab/docker-run-action@v1
        with:
          image: badouralix/zunit
